tap "homebrew/bundle"
brew "autoconf"
brew "automake"
brew "openssl@3"
brew "ruby"
brew "cocoapods", link: false
brew "coreutils"
brew "libksba"
brew "libtool"
brew "openssl@1.1"
brew "pkg-config"
brew "tree"
brew "watchman"
brew "zlib"
cask "kitty"
