module.exports = {
  MAP_KEY: 'AIzaSyCFc3Tb7cmZhqbkBHxuW_5-YHVLCbFVYFk',
  ONE_SIGNAL_APP_KEY: "3311ec42-c129-4efd-9c64-182179f9b62c",
  APP_NAME: 'Enviro',
  ENTER_USERNAME: 'Enter Username',
  ENTER_PASSWORD: 'Enter Password',
  LOGIN_BUTTON: 'Login',
  FORGOT_PASSWORD: 'Forgot Password',
  DONT_HAVE_AN_ACCOUNT: "Don't have an Account?",
  REGISTER: 'Register',
  PLEASE_ENTER_EMAIL: 'Please enter a email address.',
  PLEASE_ENTER_VALID_EMAIL: 'Please enter a valid email address.',
  PLEASE_ENTER_REGISTERED_EMAIL: 'Please enter registered email address.',
  PLEASE_ENTER_PASSWORD: 'Please enter password.',
  PLEASE_ENTER_CONFIRM_PASS: 'Please enter confirm password.',
  PLEASE_ENTER_VALID_PASSWORD: 'Password must be 8 digit.',
  GET_OTP: 'Get Otp',
  BACK: 'Back',
  PASSWORD_MISMATCH: 'Confirm password does not match with password.',
  ENTER_EMAIL: 'Enter email address',
  ENTER_CONFIRM_PASS: 'Enter confirm password',
  TIMESHEET: ' Timesheet',
  WEEKLY: 'Weekly',
  MONTHLY: 'Monthly',
  DASHBOARD: 'Home',
  LOCATION_PERMISSION: 'Location Permission Required',
  LOCATION_PERMISSION_DESC:
    'This app requires location permission to function properly. Please enable the location permission.',
  ENABLE_PERMISSION: 'Enable Permission',
  CANCEL: 'Cancel',
  LOCATION_UNAVALABLE: 'Sorry! Location service UNAVAILABLE',
  HRM: 'HRM',
  PUNCH_IN: 'Punch-in',
  PUNCH_OUT: 'PUNCH-OUT',
  YOU_ARE: 'You are',
  METERS_AWAY_FROM_OFFICE: 'meters away from office',
  TIME: 'Working Hrs',
  NOTIFICATION: 'Notification',
  MARK_AS_READ: 'Mark as read',
  ALL: 'All',
  STARRED: 'Starred',
  CONFIRM: 'Confirm',
  APPROVE: 'Approve',
  YES: 'Yes',
  NO: 'No',
  EMAIL_ID: 'Email Id',
  PHONE_NO: 'Phone No',
  SUPPORT: 'Support',
  COMPANY_POLICY: 'Company Policy',
  CLIENT_MEETING: 'Client Meeting',
  CHECK_IN: 'Check-in',
  CHECK_OUT: 'CHECK_OUT',
  NEWS_BANNER: 'News Banner',
  ADD_TIMESHEET: 'Add TimeSheet',
  SUBMIT: 'Submit',
  REIMBURSEMENT: 'Reimbursement Request',
  LOGIN_WITH_OTP: 'Login with OTP',
  PRESENT: 'Present',
  LEAVE: 'Leave',
  IDLE: 'Idle',
  SELECT_DATE: 'Select Date',
  SELECT_CLIENT: 'Select Client',
  SELECT_DURATION: 'Select Duration',
  SELECT_PROJECT: 'Select Project',
  SELECT_TASK: 'Select Task',
  DURATION: 'Duration',
  SELECT_BILLING_METHOD: 'Select Billing Method',
  ENTER_YOUR_WORK_DESCRIPTION: 'Enter your work description',
  CHATBOT: 'Chat-Bot',
  CHANGE_PASSWORD: 'Change Password',
  SCAN_QR_CODE: 'Scan QR Code',
  SCAN_QR_MSG: 'Scan the code on site or on your device to check in',
  SCAN_CODE: 'Scan Code',
  SEARCH: 'Search',
  MEETING: 'Meeting',
  MY_BOOKING: 'My Booking',
  MY_MINUTES: 'My Minutes',
  CREATE: 'Create',
  CREATE_MEETING: 'Create Meeting',
  DOB: 'DOB',
  CONTACT: 'Contact',
  REPORTING_MANAGER: 'Reporting Manager',
  JOINED_SINCE: 'Joined Since',
  ACHIEVEMENT: 'Achievements',
  SKILLS: 'Skills',
  EXPERIENCE: 'Experience',
  HOBBIES: 'Hobbies',
  PROFESSIONAL_INFO: 'Professional Info.',
  PICK_FROM_GALLERY: 'Pick From Gallery',
  CAPTURE_FROM_CAMERA: 'Capture From Camera',
  PICK_IMAGE: 'Pick Image',
  PLEASE_SELECT_TYPE: 'Please Select Type',
  OK: 'Ok',
  ASK_ME_LATER: 'Ask Me Later',
  CAMERA_PERMISSION: 'Enviro App Camera Permission',
  SEARCH_RESULT: 'Search Result',
  EDIT_PROFILE: 'Edit Profile',
  EDIT: 'Edit',
  EXPERIENCE_DETAILS: 'Experience Details',
  SAVE: 'Save',
  DETAILS: 'Add Accommodation',
  ADD_NEW_EXPERIENCE: 'Add New Experience',
  MEETING: 'Meeting',
  MY_MEETING: 'My Meetings',
  MEETING_ROOM: "Meetings Room",
  MY_MINUTES: 'My Minutes',
  CREATE: 'Create',
  ADD_TITLE: 'Add Title',
  INDIA_STANDARD_TIME: 'India standard Time',
  DOES_NOT_REPEAT: 'Does not repeat',
  PEOPLE_TO_INVITE: 'People to invite',
  VIRTUAL: 'Virtual',
  BOTH: 'Both',
  ADD_NEW_PROJECT: '+ Add New Project',
  VIEW_ALL: 'View All',
  PROJECT_DETAILS: 'Project Details',
  ADD_NEW: 'Add New',
  EDUCATION_QUALIFICATION: 'Education Qualification',
  EDUCATION_DETAILS: 'Education Details',
  INSTITUTE_NAME: 'Institute Name',
  NAME: 'Name',
  ISSUING_ORGANIZATION: 'Issuing Organization',
  ISSUE_DATE: 'Issue Date',
  EXPIRY_DATE: 'Expiry Date',
  ABOUT: 'About',
  CONFIRM: 'Confirm',
  CANCEL_MEETING: 'Cancel Meeting',
  VIEW_ALL: 'View All',
  MEETINGS: 'Meetings',
  SETTINGS: 'Settings',
  MEETING_ROOMS: "Meeting Rooms",
  EMP_LEAVE_REQUEST: 'Employee Leave Request',
  REJECT: 'Reject',
  PDF_DOWNLOAD: 'PDF Download',
  NO_NOTIFICATION_FOUND: 'No Notification found.',
  ANNOUNCEMENT_KEY_LOCAL_STORAGE: 'announcement',
  NAME: 'Name',
  TITLE: 'title',
  PLEASE_ENTER_ISSUE_DATE: 'Please enter Issue Date.',
  PLEASE_ENTER_EXPIRY_DATE: 'Please enter Expiry Date.',
  PLEASE_ENTER_ISSUE_ORG: 'Please enter issue Organization.',
  PLEASE_ENTER_TITLE: 'Please enter Title.',
  NO_DATA_ADDED: "No Data Added.",
  LET_US_KNOW_MORE_ABOUT_YOU: "Let us know more about you",
  DESIGNATION: 'Designation',
  CHOOSE_HOBBIES: 'Choose Hobbies',
  EDUCATION: 'Education',
  CRETIFICATION: 'Certification',
  CRETIFICATION_DETAILS: 'Certification Details',
  EMPLOYEE_EXPERENCE: 'Employee Experience',
  END_DATE: 'End Date',
  START_DATE: 'Start Date',
  ADD_LINK: 'Add Link',
  LESS: 'Less',
  MORE: 'More',
  EDUCATION: 'Education',
  CERTIFICATION: 'Certification',
  LINKS: 'Links:',
  LINKEDIN: 'LinkedIn',
  LINKED: 'Linked',
  WEBSITE: 'Website',
  EVERY_DAY: 'Every Day',
  LEAVES_BALANCE: 'Leaves Balance',
  LEAVE_BALANCE: 'Leave Balance',
  LEAVE_REQUEST_PLUS: '+ Leave Request',
  TOTAL_LEAVE: 'Total Leave',
  LEAVE_TAKEN: 'Leave Taken',
  SICK_LEAVE: 'Sick\nLeave',
  CASUAL_LEAVE: 'Casual\nLeave',
  EARNED_LEAVE: 'Earned\nLeave',
  OPTIONAL_LEAVE: 'Optional\nLeave',
  DONE: 'Done',
  No_Experience_Added: 'No Experience Added',
  UPDATE_MEETING: 'Update Meeting',
  ATTENDANCE_REPORT: 'Attendance Report',
  APPLY: 'Apply',
  UPDATE: 'Update',
  SELECT_DURATION: 'Select Duration',
  PLEASE_ENTER_COMPANY_DESIGNATION: 'Please enter company designation',
  PLEASE_ENTER_COMPANY_NAME: 'Please enter company name',
  PLEASE_ENTER_START_DATE: 'Please select start date',
  PLEASE_SELECT_END_DATE: 'Please select end date',
  PLEASE_ENTER_PROJECT_TITLE: 'Please enter project title',
  PLEASE_SELECT_PROJECT_START_DATE: 'Please select project start date',
  PLEASE_SELECT_PROJECT_END_DATE: 'Please select project end date',
  PLEASE_ENTER_PROJECT_DESC: 'Please enter project description',
  PLEASE_ENTER_TITLE: 'Please Enter Title',
  PLEASE_SELECT_START_DATE: 'Please select start date',
  DAYS: 'Days',
  MY_LEAVE: 'My Leaves',
  LEAVE_REQUEST: 'Leave Request',
  SAVED_LEAVE: 'Saved Leaves',
  PLEASE_ENTER_COMPANY_DESIGNATION: 'Please enter company designation',
  PLEASE_ENTER_COMPANY_NAME: 'Please enter company name',
  PLEASE_ENTER_START_DATE: 'Please select start date',
  PLEASE_SELECT_END_DATE: 'Please select end date',
  PLEASE_ENTER_PROJECT_TITLE: 'Please enter project title',
  PLEASE_SELECT_PROJECT_START_DATE: 'Please select project start date',
  PLEASE_SELECT_PROJECT_END_DATE: 'Please select project end date',
  PLEASE_ENTER_PROJECT_DESC: 'Please enter project description',
  PLEASE_ENTER_TITLE: 'Please Enter Title',
  PLEASE_SELECT_START_DATE: 'Please select start date',
  OFFICE: 'Office',
  ONSITE: 'On-site',
  WFH: 'WFH',
  LAST_MONTH: 'Last Month',
  BILLING: 'Billing',
  NON_BILLING: 'Non Billing',
  MOCKUP: 'Mockup',
  DELETE: 'Delete',
  CANCEL_LEAVE: 'Cancel Leave',
  READ_LESS: 'Read Less',
  LESSON: 'Lesson',
  MODULE: 'Modules',
  DESCRIPTION: 'Description',
  SKILL_COVERED: 'Skills Covered',
  Transcript: 'Transcript',
  INTERNET_CONNECTION: 'Please check your Internet Connection.',
  RECENT_CHAT: 'Recent Chat',
  SAVE_MEETING: 'Save Meeting',
  BIRTHDAY: 'Birthday & Work Aniversary',
  ANNIVERSARY: "Anniversary",
  WORK: 'Work',
  HRD: 'HRD',
  CONNECT_H: "Connect H",
  COMMUNITY: 'Community',
  DISAPPROVE: 'Disapprove',
  CANCEL: 'Cancel',
  PLAN_GO: 'Plan Go',
  REQUESTED: 'Requested',
  PAST_BOOKING: 'Past Booking',
  SAVED_DRAFT: 'Saved Draft',
  WALLET: "Wallet",
  HISTORY: "History",
  TO_MOBILE_OR_CONTACT: 'To Mobile or Contact',
  PAY: 'Pay',
  APPROVAL: 'Approval',
  BILLIMAGE: 'Bill Image',


  STARTTIME: 'Start Time',
  ENDTIME: 'End Time',
  HOURS: 'Hours',

  SKIP: 'SKIP',
  NEXT: 'Next',
  REQUEST: 'Request',
  PENDING: 'Pending',
  HR_POLICY: 'HR Policy',
  POLICY: 'Policy',
  CALENDAR_SCHEDULE: 'Calendar Schedule',
  HELP_SUPPORT: 'Help & Support',
  LOGOUT: "Logout",
  SUCESS: "Sucess",
  FAILED: 'Failed',
  Connection_Lost: "Connection Lost",
  Check_Connection: "Check Connection",
  DELETE_NOTIFICATION: "Are you sure you want delete?",
  COPY_FROM_PREVIOUS_DATE: 'Copy From Previous Date',
  INFO_MSG: 'Upon selecting "Copy From Previous Data" and submitting, the most recent timesheet will be pasted to the current date. \n\n i.e.: If you are filling out a timesheet for January 15th, selecting "Copy from Previous Data" and submitting will show your last filled-out timesheet. So if you last filled out the timesheet on January 10th, then the data from January 10th will be pasted on January 11th. To make changes, simply click on the timesheet you want to edit from the dashboard.'


};
