module.exports = {
  LOGIN: 'Login',
  FORGOT_PASSWORD: 'ForgotPassword',
  REGISTER: 'Register',
  PROFILE: 'Profile',
  TIMESHEET: 'Timesheet',
  WEEKLY_TIMESHEET: 'WeeklyTimeSheet',
  MONTHY_TIMESHEET: 'MonthlyTimeSheet',
  ATTENDANCE: 'Attendance',
  DASHBOARD: "Dashboard",
  DRAWER: 'Drawer',
  LOGIN_WITH_OTP: 'LoginWithOtp',
  CHANGE_PASSWORD: 'ChangePassword',
  TIME_SHEET_DETAILS: 'TimeSheetDetails',
  SCAN_CODE: 'ScanCode',
  REIMBURSEMENT: 'ReimbursementDetail',
  SEARCH_USER: 'My Directory',
  REGISTER: 'Register',
  PROFILE: 'Profile',
  WEEKLY_TIMESHEET: 'WeeklyTimeSheet',
  MONTHY_TIMESHEET: 'MonthlyTimeSheet',
  ATTENDANCE: 'Attendance',
  DASHBOARD: 'Dashboard',
  DRAWER: 'Drawer',
  CHAT_BOT: 'ChatBot',
  CHAT_BOT_HISTORY: 'ChatBotHistory',
  CONNECT_KOLA: 'ConnectKola',
  ALL_NOTIFICATION: 'AllNotification',
  HOME_NOTIFICATION: 'HomeNotification',
  STARRED_NOTIFICATION: 'StarRedNotification',
  SUPPORT: 'Support',
  COMPANY_POLICY: 'CompanyPolicy',
  CLIENT_MEETING: 'ClientMeeting',
  MEETING: 'Meetings',
  NEWS_BANNER: 'NewsBanner',
  LOGIN_WITH_OTP: 'LoginWithOtp',
  ADD_TIMESHEET: 'AddTimeSheet',
  BOTTOM_NAVIGATION: 'BOTTOM_NAVIGATION',
  COMMUNITY_HUB: 'CommunityHub',
  MEETING_ROOM_LIST: 'MeetingRoomList',
  CHANGE_PASSWORD: 'ChangePassword',
  TIME_SHEET_DETAILS: 'TimeSheetDetails',
  SCAN_CODE: 'ScanCode',
  MEETING_HOME: 'Meetings',
  BOOK_ROOM: 'BookRoom',
  MEETING_SCHEDULE: 'MeetingSchedule',
  ADD_SCHEDULE_MEETING: 'AddScheduleMeeting',
  EDIT_PROFILE: 'Edit Profile',
  PROFESSIONAL_INFO: 'Professional Info',
  EXPERIENCE_DETAILS: 'Experience Details',
  MY_PROFILE: 'My Profile',
  MY_CALENDAR: 'My Calendar',
  MY_DIRECTORY: 'My Directory',
  MY_TEAM: 'My Team',
  SETTINGS: 'Settings',
  HR_POLICY: 'HR Policy',
  ATTENDANCE_REPORT: 'Attendance Report',
  ATTENDANCE_REGULARISE: 'AttendanceRegularise',
  LEAVES: 'Leaves',
  TIMESHEETS: 'Timesheets',
  LEAVE_REPORT: 'LeaveReport',
  WFH_POLICY: 'WFHPolicy',
  MY_PROJECTS: 'MyProjects',
  SURVEYS: 'Surveys',
  MY_CTC: 'MyCTC',
  SALARY_SLIP: 'Salary Slip',
  TAX_REPORT: 'Tax Report',
  REIMBURSEMENTS: 'Gurukul',
  INVESTMENT_DECLARATION: 'InvestmentDeclaration',
  FROM_16: 'Form 16',
  MY_HR: 'My HR',
  FEEDBACK: 'Feedback',
  HELP_SUPPORT: 'Help & Support',
  ONBOARDING: 'Onboarding',
  ALUMNI_DIRECTORY: 'AlumniDirectory',
  RESIGNATION: 'Resignation',
  CHECK_IN: 'Check-in',
  LEAVE_BALANCE: 'LeaveBalance',
  MEETING_HOME: 'MeetingHome',
  MYBOOKING_LIST: 'MyBookingList',
  LEAVES_REPORT: 'Leaves Report',
  LEAVE_DASHBOARD: 'Leave Dashboard',
  NEW_LEAVE: 'New Leave',
  EDIT_MEETING: 'MeetingRoomDetails',
  HOME_STACK: 'HomeStack',
  AUTH_STACK: 'AuthStack',
  SHOW_PROFILE: 'Show Profile',
  RM_LEAVE_REQUEST: 'RmLeaveRequest',
  SELECT_BOOK_ROOM: 'Select Book Rom',
  MEETING_DETAILS: 'MeetingDetails',
  MEETING_LIST_DETAILS: 'MEETING_LIST_DETAILS',
  CHECK_IN_QR: 'Punch-in',
  EVENT_POLL_SCREEN: 'EventPollScreen',
  EVENT_PRESENTER_SCREEN: 'EventPresenterScreen',
  EVENT_HOME_SCREEN: 'EventHomeScreen',
  ALL_EVENTS: 'AllEventsScreen',
  COMMUNITIES: 'CommunitiesScreen',
  HUB_STACK: 'HubStack',
  EVENT_STACK: 'EventStack',
  HUB_TABS: 'HubTabs',
  EVENT_FORM_SCREEN: 'EventForm',
  EVENT_DETAILS_SCREEN: 'EventDetails',
  PROFESSIONALMANAGERDETAIL: 'ProfessionalManagerDetail',
  EXPERIENCEMANAGERDETAIL: 'ExperienceManagerDetail',
  STORIESVIEW: 'StoriesView',
  COURSES: 'Courses',
  CATEGORIES: 'Categories',
  ALL_COURSES: 'AllCourses',
  MARKETING_LEADERSHIP: 'MarketingLeadership',
  MARKETING_QUESTION: 'MarketingQuestion',
  PUNCH_IN: 'Punch-in',
  PUNCH_OUT: 'PUNCH-OUT',
  GURUKUL: 'Gurukul',
  CATEGORIES_DETAILS: 'CategoriesDetails',


  PROJECT_MANAGEMENT: 'ProjectManagement',
  MY_TEAM_AVAILABILITY: 'MyTeamAvailability',
  VIEW_PROFILE: 'View Profile',

  //{*****Settings*****}
  TASK_MANAGER: 'Task Manager',
  CONNECT: 'Connect',
  COMMUNITY: 'Community',
  PRIORITY_SETTINGS: 'Priority Settings',

  DISPLAY_MODE: 'Display Mode',
  DATE_TIME_FORMAT: 'Date Time Format',
  TAB_BAR: 'Tab Bar',

  CALENDAR: 'Calendar',
  SIGN_OUT: 'Sign Out',
  EVENTSTORIES: 'EventStories',
  BIRTHDAY_NOTIFICATION: "birthdayNotification",
  ANNIVERSARY_NOTIFICATION: "anniversaryNotification",
  CONNECTH_NOTIFICATION: "connect_h_notification",
  CUMMUNITY_NOTIFICATION: "cumunityNotification",
  HRD_NOTIFICATION: "hrdNotification",
  WORK_NOTIFICATION: "workNotification",
  GURUKUL_RESULT: "Result",
  ALL_SOLUTION: "AllSolution",
  CERTIFICATE: "Certificate",
  LUNCHINGSCREEN: "LunchingScreen",
  INITIALLOADING: "InitialLoading",
  GURUKUL_STACK: "GurukulStack",
  GURUKU_BOTTOM_NNAVIGATION: "GurukulBottomNavigation",
  GURUKU_MAIN_STACK: "GurukulMainStack",
  CONNECT_TAB: 'ConnectHTab',
  TEAM_CONNECT: 'TeamConnects',
  FLIGHT_BOOKING: "Flight",
  TRAIN_BOOKING: "Train",
  BUS_BOOKING: "Bus",
  CAB_BOOKING: "Cab",
  BOOKING_REQUEST_TAB: "BookingRequestTab",
  WALLETHISTORY: "WalletHistory",
  WALLET: 'Wallet',
  PAY: "Pay",
  PAYNOW: 'Pay Now',
  RECENT_PAYMENT: 'Recent Payment',
  SUCESS_PAY: 'Sucess Pay',
  BILL_SCREEN: 'Bill Screen',
  PAYMENT_SCREEN: 'Payment Scan',
  PLAN_G0_LIST: "PlanGoList",
  PG_DETAILS_LIST: "PGDetailsList",
  PAYMENT_OTP: "Payment Otp",
  PROJECT_DETAILS: "ProjectDetails",
  PROJECT_MANAGEMENTS_DETAILS: "ProjectManagementDetails",
  ATTENDANCE_REGULARIZATION: "Attendance Regularise",
  REQUEST_REGULARIZATION: "RequestRegularization",
  CALENDER_MEETING_LIST: "CalenderMeetingListScreen",
  COMING_SOON: 'Coming Soon',
  HOLIDAY_LIST: 'Holiday List',
  LEAVEBALANCE: 'Leave Balance',
  POLICY: 'Policy',
  PDF_VIEW: 'PdfView',
  CONTINUE_LEARNING: 'ContinueLearning',
  SAVED_COURSES: 'SavedCourses',

};
